name: Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [8.3, 8.4]
        laravel: [10.*, 11.*, 12.*]
        stability: [prefer-stable]
        include:
          - laravel: 10.*
            testbench: 8.*
            phpunit: ^10.0
          - laravel: 11.*
            testbench: 9.*
            phpunit: ^10.0
          - laravel: 12.*
            testbench: 10.*
            phpunit: ^11.5

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }} - ${{ matrix.stability }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none

      - name: Require matching PHPUnit version
        run: |
          composer require --dev "phpunit/phpunit:${{ matrix.phpunit }}" --no-interaction --no-update

      - name: Install Laravel + Testbench
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update

      - name: Update all dependencies
        run: |
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction --with-all-dependencies

      - name: Run tests
        run: vendor/bin/phpunit
